name: Run Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}

    steps:
      - name: check bpf
        run: |
          cat /boot/config-$(uname -r) | grep BPF

      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install gcc clang llvm libbpf-dev zlib1g-dev libelf-dev
          git clone --recurse-submodules https://github.com/libbpf/bpftool.git
          cd bpftool/src
          make
          sudo make install
          cd ../..
          which bpftool


      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: |
          make
          sudo make install

      - name: run tests
        run: |
          ./tests/run-tests.sh

