name: Run Test

on:
  push:
    branches: [rust]
  pull_request:
    branches: [rust]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: check bpf
        run: |
          cat /boot/config-$(uname -r) | grep BPF

      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc clang llvm libbpf-dev zlib1g-dev libelf-dev autopoint pkg-config flex bison
          git clone --recurse-submodules https://github.com/libbpf/bpftool.git
          cd bpftool/src
          make
          sudo make install
          cd ../..
          which bpftool
          clang --version

      - name: checkout
        uses: actions/checkout@v4

      - name: build and install
        run: |
          sudo ./install.sh
          trace_v3 install

      - name: run tests
        run: |
          sudo ./tests/run-tests.sh

